# Copyright 2019, akashche at redhat.com
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

trigger:
- master

variables:
  OJDKBUILD_JDK8_TAG: java-1.8.0-openjdk-1.8.0.332-1.b09
  OJDKBUILD_JDK8_DEBUG_TAG: java-1.8.0-openjdk-debug-1.8.0.332-1.b09
  OJDKBUILD_JDK8_32_TAG: java-1.8.0-openjdk-1.8.0.332-1.b09-x86
  OJDKBUILD_JDK8_32_DEBUG_TAG: java-1.8.0-openjdk-debug-1.8.0.332-1.b09-x86
  OJDKBUILD_JDK8_VS15_TAG: java-1.8.0-openjdk-1.8.0.332-1.b09-vs15
  OJDKBUILD_JDK8_VS15_DEBUG_TAG: java-1.8.0-openjdk-debug-1.8.0.332-1.b09-vs15
  OJDKBUILD_JDK8_RPMBUILD: 0
  OJDKBUILD_JDK11_TAG: java-11-openjdk-11.0.15.9-1
  OJDKBUILD_JDK11_DEBUG_TAG: java-11-openjdk-debug-11.0.15.9-1
  OJDKBUILD_JDK11_RPMBUILD: 0
  OJDKBUILD_JDK17_TAG: java-17-openjdk-17.0.3.0.6-1
  OJDKBUILD_JDK17_DEBUG_TAG: java-17-openjdk-debug-17.0.3.0.6-1
  OJDKBUILD_JDK17_RPMBUILD: 0

jobs:

- job: jdk8
  timeoutInMinutes: 0
  pool:
    vmImage: "windows-2022"
  steps:
  - script: |
      @echo on
      git config --global core.autocrlf false || exit /b 1
      call resources\scripts\modules.bat resources/profiles/jdk8_full.gitmodules.txt || exit /b 1
      rd /s /q ".git" || exit /b 1
      call "resources/scripts/set-compile-env-vs10-x86_64.bat" || exit /b 1
      mkdir build || exit /b 1
      pushd build || exit /b 1
      cmake ../src/java-1.8.0-openjdk -G "NMake Makefiles" -Dopenjdk_RPMBUILD=$(OJDKBUILD_JDK8_RPMBUILD) -Dopenjdk_ENABLE_OPENJFX=ON -Dopenjdk_ENABLE_BOOTCYCLE=ON -Dopenjdk_ENABLE_CLEANUP=ON -Dopenjfx_ENABLE_CLEANUP=ON || exit /b 1
      nmake installer || exit /b 1
      popd || exit /b 1
      dir dist || exit /b 1
      if not "$(OJDKBUILD_JDK8_RPMBUILD)" == "0" tools\ghr\ghr.exe -t $(OJDKBUILD_GITHUB_TOKEN) -u ojdkbuild -r ojdkbuild -c $(Build.SourceVersion) $(OJDKBUILD_JDK8_TAG) dist || exit /b 1
    enabled: false

- job: jdk8_debug
  timeoutInMinutes: 0
  pool:
    vmImage: "windows-2022"
  steps:
  - script: |
      @echo on
      git config --global core.autocrlf false || exit /b 1
      call resources\scripts\modules.bat resources/profiles/jdk8.gitmodules.txt || exit /b 1
      rd /s /q ".git" || exit /b 1
      call "resources/scripts/set-compile-env-vs10-x86_64.bat" || exit /b 1
      mkdir build || exit /b 1
      pushd build || exit /b 1
      cmake ../src/java-1.8.0-openjdk -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Debug -Dopenjdk_RPMBUILD=$(OJDKBUILD_JDK8_RPMBUILD) -Dopenjdk_ENABLE_CLEANUP=ON || exit /b 1
      nmake zip_debug || exit /b 1
      popd || exit /b 1
      dir dist || exit /b 1
      if not "$(OJDKBUILD_JDK8_RPMBUILD)" == "0" tools\ghr\ghr.exe -t $(OJDKBUILD_GITHUB_TOKEN) -u ojdkbuild -r ojdkbuild -c $(Build.SourceVersion) $(OJDKBUILD_JDK8_DEBUG_TAG) dist || exit /b 1
    enabled: false

- job: jdk8_32
  timeoutInMinutes: 0
  pool:
    vmImage: "windows-2022"
  steps:
  - script: |
      @echo on
      git config --global core.autocrlf false || exit /b 1
      call resources\scripts\modules.bat resources/profiles/jdk8_full.gitmodules.txt || exit /b 1
      pushd deps || exit /b 1
      rd /s /q jmc-mvnrepo || exit /b 1
      rd /s /q jmc-p2repo || exit /b 1
      popd || exit /b 1
      pushd upstream || exit /b 1
      rd /s /q jmc || exit /b 1
      popd || exit /b 1
      rd /s /q ".git" || exit /b 1
      call "resources/scripts/set-compile-env-vs10-x86.bat" || exit /b 1
      mkdir build || exit /b 1
      pushd build || exit /b 1
      cmake ../src/java-1.8.0-openjdk -G "NMake Makefiles" -Dopenjdk_RPMBUILD=$(OJDKBUILD_JDK8_RPMBUILD) -Dopenjdk_ENABLE_32_BIT=ON -Dopenjdk_ENABLE_JMC=OFF -Dopenjdk_ENABLE_OPENJFX=ON -Dopenjdk_ENABLE_BOOTCYCLE=ON -Dopenjdk_ENABLE_CLEANUP=ON -Dopenjfx_ENABLE_CLEANUP=ON || exit /b 1
      nmake installer || exit /b 1
      popd || exit /b 1
      dir dist || exit /b 1
      if not "$(OJDKBUILD_JDK8_RPMBUILD)" == "0" tools\ghr\ghr.exe -t $(OJDKBUILD_GITHUB_TOKEN) -u ojdkbuild -r ojdkbuild -c $(Build.SourceVersion) $(OJDKBUILD_JDK8_32_TAG) dist || exit /b 1
    enabled: false

- job: jdk8_32_debug
  timeoutInMinutes: 0
  pool:
    vmImage: "windows-2022"
  steps:
  - script: |
      @echo on
      git config --global core.autocrlf false || exit /b 1
      call resources\scripts\modules.bat resources/profiles/jdk8.gitmodules.txt || exit /b 1
      rd /s /q ".git" || exit /b 1
      call "resources/scripts/set-compile-env-vs10-x86.bat" || exit /b 1
      mkdir build || exit /b 1
      pushd build || exit /b 1
      cmake ../src/java-1.8.0-openjdk -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Debug -Dopenjdk_RPMBUILD=$(OJDKBUILD_JDK8_RPMBUILD) -Dopenjdk_ENABLE_32_BIT=ON -Dopenjdk_ENABLE_CLEANUP=ON || exit /b 1
      nmake zip_debug || exit /b 1
      popd || exit /b 1
      dir dist || exit /b 1
      if not "$(OJDKBUILD_JDK8_RPMBUILD)" == "0" tools\ghr\ghr.exe -t $(OJDKBUILD_GITHUB_TOKEN) -u ojdkbuild -r ojdkbuild -c $(Build.SourceVersion) $(OJDKBUILD_JDK8_32_DEBUG_TAG) dist || exit /b 1
    enabled: false

- job: jdk8_vs15
  timeoutInMinutes: 0
  pool:
    vmImage: "windows-2022"
  steps:
  - script: |
      @echo on
      git config --global core.autocrlf false || exit /b 1
      call resources\scripts\modules.bat resources/profiles/jdk8.gitmodules.txt || exit /b 1
      git submodule update --init tools/toolchain/sdk10_17763
      git submodule update --init tools/toolchain/vs2017bt_15936
      rd /s /q ".git" || exit /b 1
      call "resources/scripts/set-compile-env-vs15-x86_64-jdk8.bat" || exit /b 1
      mkdir build || exit /b 1
      pushd build || exit /b 1
      cmake ../src/java-1.8.0-openjdk -G "NMake Makefiles" -Dopenjdk_RPMBUILD=$(OJDKBUILD_JDK8_RPMBUILD) -Dopenjdk_ENABLE_VS15=ON -Dopenjdk_ENABLE_BOOTCYCLE=ON || exit /b 1
      nmake installer || exit /b 1
      popd || exit /b 1
      dir dist || exit /b 1
    enabled: false

- job: jdk8_vs15_debug
  timeoutInMinutes: 0
  pool:
    vmImage: "windows-2022"
  steps:
  - script: |
      @echo on
      git config --global core.autocrlf false || exit /b 1
      call resources\scripts\modules.bat resources/profiles/jdk8.gitmodules.txt || exit /b 1
      git submodule update --init tools/toolchain/sdk10_17763
      git submodule update --init tools/toolchain/vs2017bt_15936
      rd /s /q ".git" || exit /b 1
      call "resources/scripts/set-compile-env-vs15-x86_64-jdk8.bat" || exit /b 1
      mkdir build || exit /b 1
      pushd build || exit /b 1
      cmake ../src/java-1.8.0-openjdk -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Debug -Dopenjdk_RPMBUILD=$(OJDKBUILD_JDK8_RPMBUILD) -Dopenjdk_ENABLE_VS15=ON || exit /b 1
      nmake zip_debug || exit /b 1
      popd || exit /b 1
      dir dist || exit /b 1
    enabled: false

- job: jdk11
  timeoutInMinutes: 0
  pool:
    vmImage: "windows-2022"
  steps:
  - script: |
      @echo on
      git config --global core.autocrlf false || exit /b 1
      call resources\scripts\modules.bat resources/profiles/jdk11.gitmodules.txt || exit /b 1
      rd /s /q ".git" || exit /b 1
      call "resources/scripts/set-compile-env-vs15-x86_64.bat" || exit /b 1
      mkdir build || exit /b 1
      pushd build || exit /b 1
      cmake ../src/java-11-openjdk -G "NMake Makefiles" -Dopenjdk_RPMBUILD=$(OJDKBUILD_JDK11_RPMBUILD) -Dopenjdk_ENABLE_BOOTCYCLE=ON -Dopenjdk_ENABLE_CLEANUP=ON || exit /b 1
      nmake installer || exit /b 1
      popd || exit /b 1
      dir dist || exit /b 1
      if not "$(OJDKBUILD_JDK11_RPMBUILD)" == "0" tools\ghr\ghr.exe -t $(OJDKBUILD_GITHUB_TOKEN) -u ojdkbuild -r ojdkbuild -c $(Build.SourceVersion) $(OJDKBUILD_JDK11_TAG) dist || exit /b 1
    enabled: false

- job: jdk11_debug
  timeoutInMinutes: 0
  pool:
    vmImage: "windows-2022"
  steps:
  - script: |
      @echo on
      git config --global core.autocrlf false || exit /b 1
      call resources\scripts\modules.bat resources/profiles/jdk11.gitmodules.txt || exit /b 1
      rd /s /q ".git" || exit /b 1
      call "resources/scripts/set-compile-env-vs15-x86_64.bat" || exit /b 1
      mkdir build || exit /b 1
      pushd build || exit /b 1
      cmake ../src/java-11-openjdk -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Debug -Dopenjdk_RPMBUILD=$(OJDKBUILD_JDK11_RPMBUILD) -Dopenjdk_ENABLE_CLEANUP=ON || exit /b 1
      nmake zip_debug || exit /b 1
      popd || exit /b 1
      dir dist || exit /b 1
      if not "$(OJDKBUILD_JDK11_RPMBUILD)" == "0" tools\ghr\ghr.exe -t $(OJDKBUILD_GITHUB_TOKEN) -u ojdkbuild -r ojdkbuild -c $(Build.SourceVersion) $(OJDKBUILD_JDK11_DEBUG_TAG) dist || exit /b 1
    enabled: false

- job: jdk17
  timeoutInMinutes: 0
  pool:
    vmImage: "windows-2022"
  steps:
  - script: |
      @echo on
      git config --global core.autocrlf false || exit /b 1
      call resources\scripts\modules.bat resources/profiles/jdk17.gitmodules.txt || exit /b 1
      rd /s /q ".git" || exit /b 1
      call "resources/scripts/set-compile-env-vs16-x86_64.bat" || exit /b 1
      mkdir build || exit /b 1
      pushd build || exit /b 1
      cmake ../src/java-17-openjdk -G "NMake Makefiles" -Dopenjdk_RPMBUILD=$(OJDKBUILD_JDK17_RPMBUILD) -Dopenjdk_ENABLE_BOOTCYCLE=ON -Dopenjdk_ENABLE_CLEANUP=ON || exit /b 1
      nmake installer || exit /b 1
      popd || exit /b 1
      dir dist || exit /b 1
      if not "$(OJDKBUILD_JDK17_RPMBUILD)" == "0" tools\ghr\ghr.exe -t $(OJDKBUILD_GITHUB_TOKEN) -u ojdkbuild -r ojdkbuild -c $(Build.SourceVersion) $(OJDKBUILD_JDK17_TAG) dist || exit /b 1
    enabled: false

- job: jdk17_debug
  timeoutInMinutes: 0
  pool:
    vmImage: "windows-2022"
  steps:
  - script: |
      @echo on
      git config --global core.autocrlf false || exit /b 1
      call resources\scripts\modules.bat resources/profiles/jdk17.gitmodules.txt || exit /b 1
      rd /s /q ".git" || exit /b 1
      call "resources/scripts/set-compile-env-vs16-x86_64.bat" || exit /b 1
      mkdir build || exit /b 1
      pushd build || exit /b 1
      cmake ../src/java-17-openjdk -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Debug -Dopenjdk_RPMBUILD=$(OJDKBUILD_JDK17_RPMBUILD) -Dopenjdk_ENABLE_CLEANUP=ON || exit /b 1
      nmake zip_debug || exit /b 1
      popd || exit /b 1
      dir dist || exit /b 1
      if not "$(OJDKBUILD_JDK17_RPMBUILD)" == "0" tools\ghr\ghr.exe -t $(OJDKBUILD_GITHUB_TOKEN) -u ojdkbuild -r ojdkbuild -c $(Build.SourceVersion) $(OJDKBUILD_JDK17_DEBUG_TAG) dist || exit /b 1
    enabled: false
